## 默认端口号是 8080 我们可以把它改成 9010
#server.port=9010
## 更改访问路径    http://localhost:9010/leo/demo
#server.servlet.context-path=/leo

# 项目访问启动配置
server:
  port: 9010
  servlet:
    context-path: /leo
  tomcat:
    uri-encoding: utf-8

# MySQL 配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/2021_leo_sluggard?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

